# Generated by Django 3.2.6 on 2021-09-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='conf_passwd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='passwd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
